### ISSUE TITLE
Can you create nodejs:10-latest

### ISSUE THREAD

**Issue by stephenmoloney** [tiredofit/docker-jitsi-meet#13]
Hi,

This package looks good.

`npm install` is failing with current nodejs:9 and nodejs:8

can you create a version 10 with npm 6?

I've have to do a workaround for now which is not suitable as a PR.

`https://github.com/stephenmoloney/docker-jitsi-meet/tree/fix/bin-webpack-not-found`

**Comment by tiredofit** [comment]
Yes, absolutely. I am using them in my private repos, so let me just sanitize them and them push them up to Github. It might take a day for Dockerhub to build the images as many are dependent on the base images of Debian/Alpine/Ubuntu which forces a rebuild of all. Otherwise you could build a copy locally for the time being while the automated build process completes.

**Comment by stephenmoloney** [comment]
Thanks . Yes, I'm using a manual build for the moment of nodejs containers.

**Comment by gruberro** [comment]
@tiredofit any change to get your published Docker images tagged? Took me quite some time to find this issue. In my case the Kubernetes cluster nodes were upgraded, which caused the images to be pulled again from Docker which finally installed the broken image version. This would not have been happen if the images are tagged 😄

**Comment by tiredofit** [comment]
Hi, I tag my private images, but haven't been able to think about getting them tagged on Github/Dockerhub properly. But yes I will rebuild my workflow for the public Github images from not just :latest

**Comment by gruberro** [comment]
Sounds great! Thank you

**Comment by tiredofit** [comment]
Hi @gruberro 
I am 75% of the way done with tagging all images, so that you don't end up in a pickle again. All repositories that simply had tracked one version of a software package are tagged with :latest, the the verison number from my CHANGELOG.md. - 

The repos that were once tracking multiple software versions out of master are being split to their own branches. `:latest` will always track whatever I deem as the most recent package release with the distro of my choice (usually Alpine), and there will also be a `versionnum:latest` e.g `5:latest` or `5-alpine:latest` as they are now. The difference is that if you look on the Dockerhub you will also see tags that look like `5_alpine-2.0` again, pulled from the CHANGELOG.md in that branch.

Thanks for the kickstart to get this done, I've been meaning to for a while on Github but it was just a matter of hearing voices requesting and carving out some time in my schedule to get this done. I hope this helps.

**Comment by gruberro** [comment]
Hi @tiredofit!
That sounds great. I'm following the images I'm using and will update as soon as they are tagged!

Thank you very much! That helps a lot!!
